### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by jimfulton** [andosa/treeinterpreter#32]
How should tests be run?

I get 3 test failures using `python setup.py test` or `pytest` using Python 3.6.

```
======================================================================
FAIL: test_forest_regressor (tests.test_treeinterpreter.TestTreeinterpreter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/c97346/p/treeinterpreter/tests/test_treeinterpreter.py", line 75, in test_forest_regressor
    self.assertTrue(np.allclose(base_prediction, pred))
AssertionError: False is not true

======================================================================
FAIL: test_forest_regressor_joint (tests.test_treeinterpreter.TestTreeinterpreter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/c97346/p/treeinterpreter/tests/test_treeinterpreter.py", line 90, in test_forest_regressor_joint
    self.assertTrue(np.allclose(base_prediction, pred))
AssertionError: False is not true

======================================================================
FAIL: test_tree_regressor (tests.test_treeinterpreter.TestTreeinterpreter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/c97346/p/treeinterpreter/tests/test_treeinterpreter.py", line 40, in test_tree_regressor
    self.assertTrue(np.allclose(base_prediction, pred))
AssertionError: False is not true
```

**Comment by jimfulton** [comment]
The tests are failing because the shapes of the predictions from treeinterpeter and scikit-learn are different.

Did this change in one or the other?

**Comment by juliangilbey** [comment]
I notice that in the test `test_forest_regressor` with `ForestRegressor == RandomForestRegressor`, the shape of `pred` (the result of calling `treeinterpreter.predict`) is `(253, 1)` while the shape of `bias` is `(253,)`.  This is surely wrong?
